### ISSUE TITLE
Adding tasks

### ISSUE THREAD

**Issue by korvenhasta** [korvenhasta/awesome-todo-list#3]
### WHAT

Make a page for adding tasks

![Image](https://user-images.githubusercontent.com/51381521/210237279-2b49cbbe-237c-455b-a788-28ec66f15f6e.jpg)

### WHY

We need to make a form for adding task. We can use [react hook form](https://react-hook-form.com/)

### HOW

- [x] Cteate a new branch (feature-adding-tasks)
- [x] Create atoms / molecules for adding tasks
- [x] Add React Hook Form to the project [Get started](https://react-hook-form.com/get-started)
- [x] Make a mobile implementattion
- [x] Make a desktop implementation
- [x] Push to github
- [x] Make a PR

### Anything else

- Just create a form without sending data anywhere
- Use design from frontend mentor

**Comment by Reinoptland** [comment]
I like the issue and your todolist. 

## Questions

### Page or Modal?

Is the create page going to be 

- A seperate page (will be easier to implement when we add the database) 
- Or will this be a modal on the list page? (we will need to do some more state management in that case, when we add the database) 

### 1 Form on 2 Forms?

Do you see both of these forms on the page at once? Or do you see the second (optional one) when you've submitted the first one? 

If you see both at once: 
- I think that you can easily combine both steps into 1 form with the date input being optional. 

If you see the second form with the date after submitting the first one
- There is no button to skip the setp
- There is no button to go back to previous step

I think doing both inputs in one form will be a bit easier to execute, but only filling in one thing at a time can be a nice touch when it comes to UX.

**Comment by korvenhasta** [comment]
### Page or Modal?

I am thinking about making a popup for the form. 

### 1 Form on 2 Forms?

It looks like having 1 form looks better.

**Comment by korvenhasta** [comment]
[pull request](https://github.com/korvenhasta/awesome-todo-list/pull/4)
